
name: CI


on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: windows-latest
    steps:    
      - uses: actions/checkout@v2 
      - name: Deploy Stage
        id: apitest
        run: |
         ./apicalltest.ps1 -token ${{secrets.API_TOKEN}} -Header "application/vnd.github.v3+json" -RequestBody '{"name":"Created-From-Script-30","visibility":"private"}' -ExpectedOutput "Created-From-Script-30"    
        
  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v2
      
