
name: APITest
on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: windows-latest
    steps:    
      - uses: actions/checkout@v2 
      - name: Deploy Stage
        id: apitest
        run: |
         ./apicalltest.ps1 -token ${{secrets.API_TOKEN}} -Header ${{secrets.HEADER}} -RequestBody ${{secrets.REQUESTBODY}} -ExpectedOutput ${{secrets.EXPECTEDOUTPUT}}    
        
  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v2
      
