# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: windows-latest
  #  outputs: ${{ steps.apitest.outputs.JsonOutput }}
    steps:
      
      - uses: actions/checkout@v2
      
  
      - name: Deploy Stage
        id: apitest
        run: |
         ./apicalltest.ps1 -token ${{secrets.API_TOKEN}} -Header "application/vnd.github.v3+json" -RequestBody '{"name":"Created-From-Script-22","visibility":"private"}' -ExpectedOutput "Created-From-Script-10"    
        
  deploy:
     runs-on: ubuntu-latest
     needs: build
   
     steps:

      - uses: actions/checkout@v2
      
