name: APITest
on:
  pull_request : 
   branches: [master]
  issue_comment:
    types: [created]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:        
        - name: Checkout
          uses: actions/checkout@v2.4.0
        
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
        
          ref: ${{ github.head_ref}}
        
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
          
          
#       - name: Deploy Stage
#         uses: WorkshopOrgTest/api-composite-action@v2.3
#         with:
#           Token: ${{secrets.API_TOKEN}}
#           Header: ${{secrets.HEADER}}
#           RequestBody: ${{secrets.REQUESTBODY}}
#           ExpectedOutput: ${{secrets.EXPECTEDOUTPUT}}
    
#   deploy:
#      runs-on: ubuntu-latest
#      needs: build
#      steps:
#       - uses: actions/checkout@v2
