name: PartsUnlimited.Web.sessiondemo

on:
  workflow_dispatch:

env:
  SLN_FILE: PartsUnlimited.sln
  WEB_APP_NAME: partsplayground
  PACKAGE_TEMP_PATH: Content\D_C\a\PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\obj\Release\Package\PackageTmp

jobs:
  
  Build:
    runs-on: windows-2019
    name: ⛏️ Build Web App
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
   
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: NuGet restore
      run: nuget restore
        
    - name: Build App
      run: |
       msbuild ${{env.SLN_FILE}} /t:publish /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishDir:"${{github.workspace}}\stagingdir\publishoutput" /p:SkipInvalidConfigurations=true

    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: partsunlimited
        path: ${{github.workspace}}\stagingdir\publishoutput
    
