name: PartsUnlimited

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  SLN_FILE: PartsUnlimited.sln
 # WEB_APP_NAME: partsdemo
 # STAGING_APP_NAME: partsdemo
 # PACKAGE_TEMP_PATH: Content\D_C\a\PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\obj\Release\Package\PackageTmp

jobs:
  BuildTest:
    runs-on: windows-latest
    name: 🧪 Build and Unit Test
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
   
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
      
    - name: NuGet restore
      run: nuget restore
        
    - name: Build App
      run: |
        msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true 

    - name: Run Unit Test
      run: vstest.console.exe /Platform:x64 PartsUnlimited.UnitTests.dll
      working-directory: ${{github.workspace}}\test\PartsUnlimited.UnitTests\bin\Release
    
    - name: Details
      run: |
        cd ${{github.workspace}}/src/PartsUnlimitedWebsite/obj/Release
        dir
    
 #   - name: Copy Selenium Tests
 #     shell: pwsh
#      working-directory: ${{github.workspace}}/stagingdir
#      run: |
 #       new-item -Path . -Name 'TestAssemblies' -ItemType "directory"
 #       copy-item -Path ${{github.workspace}}\test\PartsUnlimited.SeleniumTests\bin\Release\* -Destination .\TestAssemblies -Recurse
        
    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}/bin/release
