name: PartsUnlimited
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SLN_FILE: PartsUnlimited.sln
  
  PACKAGE_TEMP_PATH: Content\D_C\a\SeleniumRepo\SeleniumRepo\src\PartsUnlimitedWebsite\obj\Release\Package\PackageTmp

jobs:
  Build:
    runs-on: windows-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
   
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: NuGet restore
      run: nuget restore
        
    - name: BuildApp
      run: |
        msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{github.workspace}}\stagingdir"   
   
    - name: Copy Tests
      shell: pwsh
      working-directory: ${{github.workspace}}/stagingdir
      run: |
        new-item -Path . -Name 'TestAssemblies' -ItemType "directory"
        copy-item -Path ${{github.workspace}}\test\PartsUnlimited.SeleniumTests\bin\Release\* -Destination .\TestAssemblies -Recurse
        
    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}/stagingdir
        
  Deploy:
    runs-on: self-hosted
    needs: [Build]
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}
        
    - name: Deploy to IIS
      run: |
        powershell Get-ChildItem -Path .\webapp -Recurse | Remove-Item -Force
        powershell expand-archive -path '*.zip' -destinationpath '.\webapp'
        powershell Copy-Item -Path ".\webapp\${{env.PACKAGE_TEMP_PATH}}\*" -Destination "C:\inetpub\PartsUnlimited" -Recurse -Force
     
    - name: DACPAC Deploy
      run: |
        & "C:\Program Files\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe" /action:Publish /SourceFile:"C:\Users\canarys123\Desktop\PULREPO\SeleniumRepo\Database\Database\pul.dacpac" /TargetDatabaseName:PartsUnlimitedDB /TargetServerName:"githubvm\SQLEXPRESS"
    
    - name: Create Test Results Folder
      run: powershell new-item -Path . -Name 'TestResults' -ItemType "directory" -Force
      
    - name: Run Selenium Tests
      working-directory: ${{github.workspace}}/TestAssemblies
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" PartsUnlimited.SeleniumTests.exe /ResultsDirectory:"${{github.workspace}}\TestResults"
        
    - name: Upload Testresults
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: TestResults
        path: ${{github.workspace}}\TestResults
