name: PRCompositeTest
on:
  pull_request:
    branches: master

jobs:
  
  build:
    runs-on: windows-latest
    steps:    
      
      - name: Deploy Stage
        uses: WorkshopOrgTest/prtestcompositeaction@v2.3
        with:
          Base: 'master'
          Head: 'development'
