name: New Pr Checks Test

on:
  issue_comment:
    types: [created]
    
  workflow_dispatch:

jobs: 
  do-stuff-when-pr-commented:        
    #if: ${{github.event.issue.pull_request }} && ${{github.actor!=dispatch-event-test[bot]}}
    if: github.event.issue.pull_request && (github.actor!='dispatch-event-test[bot]')
    name: Run this only when PR is commented
    runs-on: ubuntu-latest
    steps:
      # Get the right ref for the PR. actions/checkout clones the main/master by default
      - name: GitHub API Request
        id: request
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Get PR Details
        id: pr_details
        run: |
          echo ${{github.event.issue.number}}
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{secrets.API_TOKEN}}
          repository: WorkshopOrgTest/Testrepo
          event-type: dispatch-event
          client-payload: '{"ref": "${{ github.ref }}", "pr_number": "${{ github.event.issue.number }}", "token":"$${{secrets.GitHub_Token}}"}'
   
   

      
