name: New Pr Checks Test

on:
  issue_comment:
    types: [created]
    
  workflow_dispatch:

jobs: 
  do-stuff-when-pr-commented:        
    if: github.event.issue.pull_request 
    name: Run this only when PR is commented
    runs-on: ubuntu-latest
    steps:
      # Get the right ref for the PR. actions/checkout clones the main/master by default
      - name: GitHub API Request
        id: request
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Get PR Details
        id: pr_details
        run: |
          echo "::set-output name=pr_merge_sha::${{ fromJson(steps.request.outputs.data).merge_commit_sha }}"
          echo "::set-output name=pr_head_sha::${{ fromJson(steps.request.outputs.data).head.sha }}"
          echo "${{toJSON(steps.request.outputs.data)}}"
