name: PRTEST

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # main <-- dev-a
    # if: ${{ github.head_ref == 'dev-1' && github.base_ref == 'master' }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Comparing Branches
        id: compare
        if: ${{ github.head_ref == 'feature' && github.base_ref == 'development' }}
        run: echo ::set-output name=status::success
        continue-on-error: true
        
      - name: Get Pull Request ID
        run: |
         export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
         echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV
         

      - name: Add Comment to Pull Request if Success
        if: steps.compare.outputs.status == 'success'
        uses: actions/github-script@v5
        with:
          script: |
           await github.rest.issues.createComment({
           owner: context.repo.owner, 
           repo: context.repo.repo, 
           issue_number: ${{ env.pr_num }},
           body: 'Its Success'
           });
           
      - name: Add Comment to Pull Request if Failure
        if: steps.compare.outputs.status != 'success'
        uses: actions/github-script@v5
        with:
          script: |
           await github.rest.issues.createComment({
           owner: context.repo.owner, 
           repo: context.repo.repo, 
           issue_number: ${{ env.pr_num }},
           body: 'Incorrect PR is created'
           });
      - name: Failing the Action
        if: steps.compare.outputs.status != 'success'
        run: exit 1
           

