name: PRTEST
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    # main <-- dev-a
    # if: ${{ github.head_ref == 'dev-1' && github.base_ref == 'master' }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
#       - name: Comparing Branches
#         id: compare
#         if: ${{ github.head_ref == 'feature' && github.base_ref == 'development' }}
#         run: echo ::set-output name=status::success
#         continue-on-error: true
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Create Release
#         uses: actions/create-release@v3
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: ${{ github.ref }}
#           body: ${{steps.github_release.outputs.changelog}}
      
      - name: Get Pull Request ID
        run: |
         export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
         echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV
         echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
         echo ${{steps.github_release.outputs.changelog}} >> $GITHUB_STEP_SUMMARY

    
           
#       - name: Add Comment to Pull Request if Failure
#         if: steps.compare.outputs.status != 'success'
#         uses: actions/github-script@v5
#         with:
#           script: |
#            await github.rest.issues.createComment({
#            owner: context.repo.owner, 
#            repo: context.repo.repo, 
#            issue_number: ${{ env.pr_num }},
#            body: 'Incorrect PR is created'
#            });  
           
#       - name: Close PR and Failing action
#         if: steps.compare.outputs.status != 'success'
#         uses: actions/github-script@v5
#         with:
#           script: |
#             await github.rest.issues.update({
#                 owner: context.repo.owner,
#                 repo: context.repo.repo ,
#                 issue_number: ${{ env.pr_num }},
#                 state: closed
#               });


